### PR TITLE
Added Objective-C Nullability for Swift API Compatibility

### PR DESCRIPTION
**Pull request by AnthonyMDev**
This pull request adds the nullability annotation to make API compatibility with Swift smoother.

### CODE REVIEW

**Comment by AnthonyMDev** [comment]
Note: Because this pull request will make API changes that will effect compatibility with older versions for Swift users, the version that includes this pull request should bump the major version of the framework. (Or, since it's still in beta, the minor version from 0.1 -> 0.2)

**Comment by AnthonyMDev** [comment]
The reason this is failing CI is because the Swift example project has not been updated to use the new version.
@belkevich I don't want to waste my time fixing the example if this isn't going to make it into the repository. If you can confirm that you will accept this pull request, I'll happily make the changes to the example project.

**Comment by belkevich** [comment]
Hi! Sorry, for delay.
We don't want to release the support of nullability right now. Because many developers prefer [AppCode](https://www.jetbrains.com/objc/) rather then XCode. And unfortunately AppCode IDE doesn't have full support of nullability now. But it will coming with next update.
So, we'll accept your pull request. But a bit later.

**Comment by keith** [comment]
AppCode now supports this http://blog.jetbrains.com/objc/2015/06/new-appcode-3-2-eap-build-overrideimplement-for-swift-and-more/ it would be great if this could be merged if it's ready.

**Comment by belkevich** [comment]
Yup. I hope to release this feature on this weekend

**Comment by keith** [comment]
Any updates on this? It would be nice to include this with our iOS 9 builds.

**Comment by Reflejo** [comment]
Any updates?

**Comment by belkevich** [comment]
Merged. Please wait for release 0.2.0

**Pull request merged**
